#!/bin/sh
set -eu

stock=/mnt/vendor/firmware_mnt/image
loader=/lib/firmware/postmarketos

safe_link() {
	target=$1
	link=$2
	if [ -e "$link" ] && [ ! -L "$link" ]; then
		echo "Refusing to replace $link" >&2
		exit 1
	fi
	ln -sfn "$target" "$link"
}

findmnt -n -o OPTIONS /mnt/vendor/firmware_mnt |
	tr ',' '\n' | grep -qx ro
test -r "$stock/adspua.jsn"
test "$(cat /sys/module/firmware_class/parameters/path)" = "$loader"
mkdir -p "$loader"

for name in adsp.mdt \
	adsp.b00 adsp.b01 adsp.b02 adsp.b03 adsp.b04 adsp.b05 \
	adsp.b06 adsp.b07 adsp.b08 adsp.b09 adsp.b10 adsp.b11 \
	adsp.b12 adsp.b13 adsp.b14 adsp.b15 adsp.b16 adsp.b17 adsp.b18; do
	test -r "$stock/$name"
	safe_link "$stock/$name" "$loader/$name"
	test "$(readlink -f "$loader/$name")" = "$stock/$name"
done

echo "LMI_ADSP_FIRMWARE_PREPARE_PASS"
