context.objects = [
    { factory = adapter
      flags = [ nofail ]
      args = {
        factory.name = api.alsa.pcm.source
        node.name = lmi-microphone
        node.latency = 1024/48000
        node.description = "Microphone lmi"
        media.class = Audio/Source
        api.alsa.path = lmi_microphone
        api.alsa.disable-mmap = true
        api.alsa.period-size = 1024
        api.alsa.period-num = 4
        audio.format = S16LE
        audio.rate = 48000
        audio.channels = 1
        audio.position = [ MONO ]
        session.suspend-timeout-seconds = 5
      }
    }
]
