#!/bin/sh
exec /usr/bin/aarch64-linux-gnu-gcc \
  -nostdinc \
  -isystem/usr/lib/gcc-cross/aarch64-linux-gnu/15/include \
  -isystem/home/linuxagent/pmos-d-repro-01/analysis/gpu68-wayland-egl-init/sysroot-combined/usr/include/aarch64-linux-gnu \
  -isystem/home/linuxagent/pmos-d-repro-01/analysis/gpu68-wayland-egl-init/sysroot-combined/usr/include \
  "$@"
